# Generated by Django 5.1.7 on 2025-03-30 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tipo', models.CharField(choices=[('celular', 'Celular'), ('notebook', 'Notebook'), ('netbook', 'Netbook'), ('cpu', 'CPU'), ('all_in_one', 'All In One'), ('consola', 'Consola'), ('impresora', 'Impresora'), ('joystick', 'Joystick'), ('monitor', 'Monitor'), ('parlante', 'Parlante'), ('tablet', 'Tablet'), ('televisor', 'Televisor'), ('gps', 'GPS')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('falla_reportada', models.TextField()),
                ('condicion', models.TextField()),
                ('accesorios', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'userprofile__rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha', models.CharField(blank=True, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('ingresado', 'Ingresado'), ('en_reparacion', 'En Reparación'), ('listo', 'Listo para Retirar'), ('entregado', 'Entregado'), ('abandonado', 'Abandonado')], default='ingresado', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'userprofile__rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_creadas', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('repuestos', models.TextField(blank=True)),
                ('garantia_dias', models.PositiveIntegerField(blank=True, choices=[(30, '30 días'), (60, '60 días'), (90, '90 días')], null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_tecnicas', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ordenes.ficha')),
            ],
        ),
    ]
