# Generated by Django 5.1.7 on 2025-03-30 15:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='numero_ficha',
        ),
        migrations.AddField(
            model_name='ficha',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='fecha_reparacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 30, 15, 33, 2, 795905, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='condicion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='imei',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='estado',
            field=models.CharField(choices=[('ingresado', 'Ingresado'), ('en_revision', 'En Revisión'), ('reparado', 'Reparado'), ('entregado', 'Entregado')], default='ingresado', max_length=20),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='garantia_dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
