# Generated by Django 5.2 on 2025-06-20 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_ficha_tecnico_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='ficha',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='ordenes.ficha'),
        ),
    ]
