# Generated by Django 5.2 on 2025-07-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_alter_fichatecnica_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='fecha_reparado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
