# Generated by Django 5.2 on 2025-07-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_ficha_fecha_reparado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='accesorios',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='condicion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='falla_reportada',
        ),
        migrations.AddField(
            model_name='ficha',
            name='accesorios_entregados',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='condicion_equipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ficha',
            name='falla_reportada',
            field=models.TextField(blank=True),
        ),
    ]
