# Generated by Django 5.1.7 on 2026-02-09 19:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_remove_equipo_accesorios_remove_equipo_condicion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='tecnico_asignado',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='ficha',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='creado_por',
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(blank=True, default='', max_length=80)),
                ('dni', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('celular', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dni'], name='ordenes_cli_dni_a6eb1f_idx'), models.Index(fields=['apellido', 'nombre'], name='ordenes_cli_apellid_72f082_idx')],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('diagnosticado', 'Diagnosticado'), ('en_progreso', 'En progreso'), ('reparado', 'Reparado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20)),
                ('dispositivo_tipo', models.CharField(blank=True, default='', max_length=50)),
                ('marca', models.CharField(blank=True, default='', max_length=50)),
                ('modelo', models.CharField(blank=True, default='', max_length=80)),
                ('imei_serial', models.CharField(blank=True, default='', max_length=50)),
                ('falla_reportada', models.TextField(blank=True, default='')),
                ('condicion_equipo', models.CharField(blank=True, default='', max_length=120)),
                ('accesorios_entregados', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('diagnostico', models.TextField(blank=True, default='')),
                ('trabajo_realizado', models.TextField(blank=True, default='')),
                ('repuestos', models.TextField(blank=True, default='')),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('senia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('garantia_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('garantia_dias', models.PositiveIntegerField(default=0)),
                ('observaciones_finales', models.TextField(blank=True, default='')),
                ('fecha_finalizado', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='ordenes.cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ordenes/')),
                ('descripcion', models.CharField(blank=True, default='', max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ordenes.orden')),
            ],
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='Ficha',
        ),
        migrations.DeleteModel(
            name='FichaTecnica',
        ),
    ]
