# Generated by Django 5.1.7 on 2026-02-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_remove_ficha_equipo_remove_ficha_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='bloqueo_tipo',
            field=models.CharField(choices=[('none', 'Sin contraseña'), ('pin', 'Código (PIN)'), ('texto', 'Texto'), ('patron', 'Patrón')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='orden',
            name='bloqueo_valor',
            field=models.CharField(blank=True, default='', help_text="PIN, texto o secuencia de patrón tipo '1-2-5-8'", max_length=255),
        ),
    ]
