# Generated by Django 5.1.7 on 2026-03-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_orden_bloqueo_tipo_orden_bloqueo_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha_retirado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='observaciones_retiro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orden',
            name='retirado_por_dni',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='orden',
            name='retirado_por_nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('diagnosticado', 'Diagnosticado'), ('en_progreso', 'En progreso'), ('reparado', 'Reparado'), ('finalizado', 'Finalizado'), ('retirado', 'Retirado')], default='pendiente', max_length=20),
        ),
    ]
